# Generated by Django 4.1.1 on 2022-11-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdown_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('reg_time', models.DateTimeField()),
                ('reg_name', models.TextField()),
                ('reg_com', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='EventCountDown',
        ),
    ]
